# Generated by Django 3.1.6 on 2021-02-27 15:48

import common.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'female'), ('M', 'male')], max_length=1, verbose_name='gender')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[common.validators.validate_not_empty, common.validators.email_validator])),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[common.validators.mobile_length_validator, common.validators.mobile_validator, common.validators.validate_not_empty])),
                ('password', models.CharField(max_length=10)),
                ('bio', models.TextField(blank=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False)),
                ('friends', models.ManyToManyField(blank=True, null=True, to='user.User')),
            ],
        ),
    ]
