# Generated by Django 3.1.4 on 2021-02-26 16:34

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[common.validators.validate_not_empty, common.validators.email_validator]),
        ),
    ]
