# Generated by Django 3.1.6 on 2021-02-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_friendrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'ordering': ['-created']},
        ),
    ]
