# Generated by Django 3.1.6 on 2021-02-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_view_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='View_profile',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.AddField(
            model_name='following',
            name='followed',
            field=models.ManyToManyField(related_name='followed', to='user.User'),
        ),
        migrations.AddField(
            model_name='following',
            name='follower',
            field=models.ManyToManyField(related_name='follower', to='user.User'),
        ),
        migrations.AddField(
            model_name='following',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
