# Generated by Django 3.1.6 on 2021-03-01 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210301_1203'),
        ('post', '0002_auto_20210301_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post_id', 'user_id')},
        ),
    ]
