# Generated by Django 3.1.6 on 2021-02-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210227_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='View_profile',
            field=models.BooleanField(default=False),
        ),
    ]
