# Generated by Django 3.1.6 on 2021-04-03 08:46

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210403_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[common.validators.email_validator]),
        ),
    ]
